### ISSUE TITLE
Crashes on files in /

### ISSUE THREAD

**Issue by martinvonwittich** [KrystianD/borg-ncdu-analyzer#2]
I used `borg-ncdu-analyzer` succesfully before, but it crashes on my most recent backup (the JSON output lines are debug output from a `print(line)` I inserted into the code):

```
martin borg # python3 /home/martin/borg-ncdu-analyzer/borg_ncdu_analyzer.py  ./::archive
Dumping and processing archive...
b'{"type": "d", "mode": "drwxr-xr-x", "user": "root", "group": "root", "uid": 0, "gid": 0, "path": ".", "healthy": true, "source": "", "linktarget": "", "flags": null, "mtime": "2020-05-24T18:56:04.382781", "size": 0}\n'
b'{"type": "d", "mode": "drwx------", "user": "root", "group": "root", "uid": 0, "gid": 0, "path": "lost+found", "healthy": true, "source": "", "linktarget": "", "flags": null, "mtime": "2011-10-24T23:20:06.000000", "size": 0}\n'
b'{"type": "-", "mode": "-rw-------", "user": "root", "group": "root", "uid": 0, "gid": 0, "path": ".bash_history", "healthy": true, "source": "", "linktarget": "", "flags": null, "mtime": "2015-10-11T17:48:52.276437", "size": 52}\n'
Received SIGTERM
Traceback (most recent call last):
  File "/home/martin/borg-ncdu-analyzer/borg_ncdu_analyzer.py", line 179, in <module>
    main()
  File "/home/martin/borg-ncdu-analyzer/borg_ncdu_analyzer.py", line 143, in main
    analyzer.process_lines(read_lines_from_process(p))
  File "/home/martin/borg-ncdu-analyzer/borg_ncdu_analyzer.py", line 94, in process_lines
    self._fs_cache[parent_dir].add_entry(entry)
KeyError: ''
```

I believe it crashes on files that were in `/` when the backup ran, in this case `.bash_history`. The `parent_dir` of these files is `""`, but as that has never been added as a directory, the code crashes here.

**Comment by KrystianD** [comment]
Thank you @martinvonwittich, will look into this

**Comment by KrystianD** [comment]
Fixed. @martinvonwittich I would be grateful if you could test it on your dataset.

**Comment by martinvonwittich** [comment]
Yup, everything works fine now! Thanks!
